version: '3.8'
services:
  model-api:
    build:
      context: src/service/docker_build
      dockerfile: Dockerfile
    container_name: model-api
    ports:
      - "${PORT_PREDICT:-8000}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-8000}
    # volumes:  # не нужен для production